version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-web
    restart: always
    ports:
      - 27017:27017
    volumes:
      - C:/docker-data/mongo-web:/data/db
    network_mode: bridge
